[package]
name = "compiler"
version = "0.1.0"
authors = ["TrolledWoods <trolledwoods@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chashmap = "2.2.2"
lazy_static = "1.4.0"
